# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://gitlab.youtune.tech/pymirror/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://gitlab.youtune.tech/pymirror/isort
    rev: 7.0.0
    hooks:
      - id: isort

  - repo: https://gitlab.youtune.tech/pymirror/black
    rev: 25.9.0
    hooks:
      - id: black

  - repo: https://gitlab.youtune.tech/pymirror/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-black"]

  - repo: local
    hooks:
      - id: check-inline-comments
        name: Check for inline comments in functions
        entry: python .hooks/check_inline_comments.py
        language: python
        types: [python]
        stages: [pre-commit]
