#!/bin/bash
set -e
# -----------------------------------------------------------------------------
# 操作系统基线调优脚本 (V2.1 - PCIe 总线追踪修复版)
# 引用依据: 《Nginx 移植&调优指南》 第 3.3 节 操作系统调优
# -----------------------------------------------------------------------------

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$SCRIPT_DIR/env.sh"

if [ "$(id -u)" -ne 0 ]; then
    log_err "操作系统调优需要 root 权限，请使用 sudo 执行。"
    exit 1
fi

# 确保 ethtool 存在，用于获取 PCIe 总线号
if ! command -v ethtool &> /dev/null; then
    log_info "正在安装 ethtool 用于硬件探测..."
    yum install -y ethtool > /dev/null 2>&1
fi

log_info ">>> [Step 1] 开始应用鲲鹏 920 操作系统性能基线 (V2.1) <<<"

# --- 1. 禁用 irqbalance (引用依据: 指南 3.3.5 节, P55) ---
log_info "[3.3.5] 停止 irqbalance 服务以进行手动中断绑定..."
if systemctl is-active --quiet irqbalance; then
    systemctl stop irqbalance.service || true
    systemctl disable irqbalance.service || true
    log_info "  -> irqbalance 已停止并禁用。"
else
    log_info "  -> irqbalance 未运行，无需操作。"
fi

# --- 2. 网卡中断手动绑定 (引用依据: 指南 3.3.5 节, P56) ---
log_info "[3.3.5] 正在执行网卡中断多队列亲和性绑定..."

# 1. 物理网卡探测
ROUTE_IF=$(ip route get 8.8.8.8 2>/dev/null | awk '{print $5}' | head -1)
if [[ -z "$ROUTE_IF" || "$ROUTE_IF" == "lo" || "$ROUTE_IF" == *"docker"* || "$ROUTE_IF" == *"virbr"* ]]; then
    # 尝试找第一个非虚拟的物理网卡
    INTERFACE=$(ls -l /sys/class/net/ | grep -v virtual | head -n 1 | awk '{print $9}')
    if [ -z "$INTERFACE" ]; then
        # 兜底：找 eth 或 enp 开头的
        INTERFACE=$(ls /sys/class/net | grep -E '^(en|eth)' | head -1)
    fi
    log_info "  -> 路由接口判定为虚拟，切换至物理接口探测: $INTERFACE"
else
    INTERFACE="$ROUTE_IF"
fi

if [ -n "$INTERFACE" ]; then
    log_info "  -> 锁定目标物理网卡: [ $INTERFACE ]"

    # === 核心修复：通过 ethtool 获取 PCIe Bus ID ===
    # 鲲鹏的中断名通常包含 Bus ID (如 0000:7d:00.0) 而不是接口名
    BUS_INFO=$(ethtool -i $INTERFACE 2>/dev/null | grep 'bus-info' | awk '{print $2}')

    if [ -n "$BUS_INFO" ]; then
        log_info "  -> 获取到 PCIe 总线 ID: [ $BUS_INFO ]"
        # 使用总线 ID 搜索中断号
        IRQS=$(grep "$BUS_INFO" /proc/interrupts | awk '{print $1}' | sed 's/://')
    else
        log_err "  -> 无法获取 Bus ID，尝试使用接口名直接搜索..."
        IRQS=$(grep "$INTERFACE" /proc/interrupts | awk '{print $1}' | sed 's/://')
    fi

    # 检查是否获取到中断号
    if [ -z "$IRQS" ]; then
        log_err "  -> 警告: 即使使用 Bus ID ($BUS_INFO) 也未找到中断号。请检查 /proc/interrupts 格式。"
    else
        # 统计中断数量，决定怎么绑
        IRQ_COUNT=$(echo "$IRQS" | wc -w)
        log_info "  -> 发现 $IRQ_COUNT 个中断队列，准备绑定至 Node 1 (Core 32+)..."

        CORE_IDX=$NGINX_WORKER_COUNT # 从 32 开始绑定 (Node 1)
        BIND_COUNT=0

        for IRQ in $IRQS; do
            # 限制绑定范围，只用 Node 1-3 (32-127)，留出 Node 0 给 Nginx
            if [ $CORE_IDX -le 127 ]; then
                if [ -f "/proc/irq/$IRQ/smp_affinity_list" ]; then
                    echo $CORE_IDX > /proc/irq/$IRQ/smp_affinity_list
                    # 减少日志刷屏，只打印前3个和最后1个，或者每10个打印一次
                    if (( BIND_COUNT < 3 )) || (( BIND_COUNT % 10 == 0 )); then
                         log_info "  -> [IRQ Bind] 中断号 $IRQ ($BUS_INFO) >>> CPU Core $CORE_IDX"
                    fi
                    CORE_IDX=$((CORE_IDX + 1))
                    BIND_COUNT=$((BIND_COUNT + 1))
                fi
            else
                # 如果核心用完了，循环回到 32 (Round Robin)
                CORE_IDX=$NGINX_WORKER_COUNT
            fi
        done
        log_info "  -> 绑定完成: 共处理 $BIND_COUNT 个中断队列。"
    fi
else
    log_err "❌ 严重错误: 未找到有效的物理网卡，跳过中断绑定。"
fi

# --- 3. 内核参数调优 (引用依据: 指南 3.3.3 节, P53-P54 表3-1) ---
log_info "[3.3.3] 正在配置 /etc/sysctl.conf 内核网络协议栈..."
cat <<EOF > /etc/sysctl.d/99-kunpeng-nginx.conf
# 鲲鹏 Nginx 调优基线参数 - Generated by PIPA Setup
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.ip_local_port_range = 1024 65535
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 262144
net.core.netdev_max_backlog = 262144
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
EOF
sysctl -p /etc/sysctl.d/99-kunpeng-nginx.conf > /dev/null
log_info "✅ 内核参数已加载 (详情见 /etc/sysctl.d/99-kunpeng-nginx.conf)。"

# --- 4. 文件描述符上限 (引用依据: 指南 3.3.1 节, P52) ---
log_info "[3.3.1] 正在调整系统句柄限制 (limits.conf)..."
LIMITS_FILE="/etc/security/limits.conf"
if ! grep -q "102400" "$LIMITS_FILE"; then
    # 备份
    cp "$LIMITS_FILE" "${LIMITS_FILE}.bak"
    echo "* soft nofile 102400" >> "$LIMITS_FILE"
    echo "* hard nofile 102400" >> "$LIMITS_FILE"
    log_info "  -> 已追加 limits 配置。"
else
    log_info "  -> limits 配置已存在，跳过。"
fi
# 尝试对当前 shell 生效
ulimit -n 102400
log_info "✅ 系统调优任务全流程执行完毕。"
