import pytest
from click.testing import CliRunner
from pathlib import Path
import shutil

from src.commands.sample import sample
from src.parsers.perf_stat_timeseries_parser import parse_perf_stat_timeseries
from src.parsers.sar_timeseries_parser import parse_sar_timeseries

# 将此文件中的所有测试标记为 'integration'
pytestmark = pytest.mark.integration


@pytest.fixture(scope="module")
def live_sample_output_dir(tmp_path_factory) -> Path:
    """
    A fixture that runs 'pipa sample' once to generate real collector output,
    and yields the path to the unpacked results directory.
    This is a module-scoped fixture to avoid re-running the
    sample command for every test.
    """
    # 使用 tmp_path_factory 来创建一个在整个测试会话中都存在的临时目录
    base_temp_dir = tmp_path_factory.mktemp("integration_assets")
    pipa_archive_path = base_temp_dir / "integration_run.pipa"
    unpacked_dir = base_temp_dir / "unpacked"
    unpacked_dir.mkdir()

    runner = CliRunner()
    # 我们使用 'direct' 模式进行一次快速、真实的采样
    result = runner.invoke(
        sample,
        [
            "--workload",
            "stress_cpu",
            "--intensity",
            "1",  # 使用最低强度以加快测试速度
            "--duration",
            "2",  # 采样2秒即可
            "--output",
            str(pipa_archive_path),
        ],
        catch_exceptions=False,  # 在测试中，我们希望异常能直接抛出
    )

    assert result.exit_code == 0, f"pipa sample command failed: {result.output}"
    assert pipa_archive_path.exists(), ".pipa archive was not created."

    # 解压归档文件以供测试使用
    # .pipa 文件实际上是 gztar 格式，需要明确指定格式
    # 使用 filter='data' 以避免 Python 3.14 的废弃警告
    shutil.unpack_archive(
        pipa_archive_path, unpacked_dir, format="gztar", filter="data"
    )

    # 在解压后的目录中找到第一个 level 目录 (例如 "intensity_1")
    level_dir = next(d for d in unpacked_dir.iterdir() if d.is_dir())
    assert level_dir, "No level directory found in unpacked archive."

    return level_dir


def test_perf_parser_with_live_data(live_sample_output_dir):
    """
    Tests that the perf_stat parser can successfully process a file
    generated by a real `pipa sample` run.
    """
    perf_file = live_sample_output_dir / "perf_stat.txt"
    assert perf_file.exists(), "perf_stat.txt was not generated by the sample command."

    content = perf_file.read_text()
    assert content, "perf_stat.txt is empty."

    df = parse_perf_stat_timeseries(content)

    assert not df.empty, "Parsing live perf_stat.txt resulted in an empty DataFrame."
    assert "timestamp" in df.columns
    assert "event_name" in df.columns
    assert "value" in df.columns


def test_sar_parser_with_live_data(live_sample_output_dir):
    """
    Tests that the sar parser can successfully process a file
    generated by a real `pipa sample` run.
    """
    sar_file = live_sample_output_dir / "sar_cpu.txt"
    assert sar_file.exists(), "sar_cpu.txt was not generated by the sample command."

    content = sar_file.read_text()
    # sar -A 的输出很大，我们只检查它非空
    assert content, "sar_cpu.txt is empty."

    results = parse_sar_timeseries(content)

    assert results, "Parsing live sar_cpu.txt resulted in an empty dictionary."
    assert "cpu" in results, "The 'cpu' block was not parsed from live sar data."
    assert not results["cpu"].empty, "The 'cpu' DataFrame is empty after parsing."
