{
 "title": "ShowMeYourPIPA",
 "description": "Metrics visualization of PIPA",
 "time": { "from": "2024-07-21T21:48:52.737Z", "to": "2024-07-22T09:48:52.737Z" },
 "templating": {
  "list": [
   { "name": "Database", "query": "frser-sqlite-datasource" },
   {
    "name": "Table",
    "query": "SELECT name FROM sqlite_master WHERE type = \"table\""
   },
   { "name": "Record", "query": "SELECT record FROM $Table;" },
   {
    "name": "Info",
    "query": "SELECT \"'\" || workload || '-' || username || '-' || platform || '-' || upload_time || \"'\" FROM $Table WHERE Record = \"${Record}\";"
   }
  ]
 },
 "panels": [
  { "title": "All Datas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Show Me Your Datas",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "queryText": "select username as Owner, workload AS Workload, \ntransactions AS \"Throught\",\nthroughput as \"Throught/s\",\ncycles_per_second AS \"Cycles/s\",\ninstructions_per_second AS \"Insts/s\",\nCPI AS \"Cycles/Insts\", cycles_per_requests AS \"Cycles/REQ\",\ncpu_frequency_mhz AS \"CPU Freq(MHz)\",\npath_length AS \"Path Length\", platform AS Platform, hw_info AS \"HW Config\", \nsw_info AS \"SW Config\", used_threads AS \"Logical Cores\",\nrecord AS \"Record\",\ncomment AS \"Comment\" from \"$Table\";",
     "rawQueryText": "select username as Owner, workload AS Workload, \ntransactions AS \"Throught\",\nthroughput as \"Throught/s\",\ncycles_per_second AS \"Cycles/s\",\ninstructions_per_second AS \"Insts/s\",\nCPI AS \"Cycles/Insts\", cycles_per_requests AS \"Cycles/REQ\",\ncpu_frequency_mhz AS \"CPU Freq(MHz)\",\npath_length AS \"Path Length\", platform AS Platform, hw_info AS \"HW Config\", \nsw_info AS \"SW Config\", used_threads AS \"Logical Cores\",\nrecord AS \"Record\",\ncomment AS \"Comment\" from \"$Table\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "${Info}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "Record" },
  {
   "title": "Show You My Data",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "queryText": "SELECT transactions AS \"Throught\", \nthroughput AS \"Throught/s\", \ncycles_per_second AS \"Cycles/s\",\ninstructions_per_second AS \"Insts/s\",\ncpu_frequency_mhz AS \"CPU Freq(MHz)\",\nCPI AS \"Cycles/Insts\", cycles_per_requests AS \"Cycles/REQ\", path_length AS \"Path Length\", \nhw_info AS \"HW Config\", \nsw_info AS \"SW Config\", \nused_threads AS \"Logical Cores\" from \"$Table\" WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT transactions AS \"Throught\", \nthroughput AS \"Throught/s\", \ncycles_per_second AS \"Cycles/s\",\ninstructions_per_second AS \"Insts/s\",\ncpu_frequency_mhz AS \"CPU Freq(MHz)\",\nCPI AS \"Cycles/Insts\", cycles_per_requests AS \"Cycles/REQ\", path_length AS \"Path Length\", \nhw_info AS \"HW Config\", \nsw_info AS \"SW Config\", \nused_threads AS \"Logical Cores\" from \"$Table\" WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Avg CPU Utils",
   "type": "piechart",
   "description": "Avearage CPU Utilization",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT cpu_usr AS \"usr%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_usr AS \"usr%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_nice AS \"nice%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_nice AS \"nice%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_sys AS \"sys%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_sys AS \"sys%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_iowait AS \"iowait%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_iowait AS \"iowait%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_steal AS \"steal%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_steal AS \"steal%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_irq AS \"irq%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_irq AS \"irq%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_soft AS \"soft%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_soft AS \"soft%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_guest AS \"guest%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_guest AS \"guest%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_gnice AS \"gnice%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_gnice AS \"gnice%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT cpu_idle AS \"idle%\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT cpu_idle AS \"idle%\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Avg Mem Utils",
   "type": "piechart",
   "description": "Average Memory Utilization",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT kbmemfree AS \"memfree\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT kbmemfree AS \"memfree\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT kbmemused AS \"memused\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT kbmemused AS \"memused\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT kbbuffers AS \"buffers\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT kbbuffers AS \"buffers\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT kbcached AS \"cached\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT kbcached AS \"cached\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT kbslab AS \"slab\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT kbslab AS \"slab\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT kbcommit AS \"memcommit\" FROM $Table WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT kbcommit AS \"memcommit\" FROM $Table WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Average Mem Utils",
   "type": "table",
   "description": "Average Memory Utilization",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "queryText": "SELECT kbavail AS \"memavail\",\npercent_commit AS \"memcommit%\",\npercent_memused AS \"memused%\",\nkbactive AS \"memactive\",\nkbinact AS \"meminact\",\nkbdirty AS \"memdirty\",\nkbanonpg AS \"memanonpg\",\nkbkstack AS \"memkstack\",\nkbpgtbl AS \"mempgtbl\",\nkbvmused AS \"memvmused\",\nkbcommit AS \"memcommit\" FROM \"$Table\" \nWHERE Record = \"$Record\";",
     "rawQueryText": "SELECT kbavail AS \"memavail\",\npercent_commit AS \"memcommit%\",\npercent_memused AS \"memused%\",\nkbactive AS \"memactive\",\nkbinact AS \"meminact\",\nkbdirty AS \"memdirty\",\nkbanonpg AS \"memanonpg\",\nkbkstack AS \"memkstack\",\nkbpgtbl AS \"mempgtbl\",\nkbvmused AS \"memvmused\",\nkbcommit AS \"memcommit\" FROM \"$Table\" \nWHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Average DIsk I/O Utils",
   "type": "table",
   "description": "Average DIsk I/O Utilization",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "queryText": "SELECT dev AS \"Dev\",\ntps AS \"Trans/s\",\ndisk_await AS \"Disk Await\",\npercent_disk_util AS \"Disk Util%\",\nrkB_s AS \"ReadkB/s\",\nwkB_s AS \"WritekB/s\",\ndkB_s AS \"DiskkB/s\",\nareq_sz AS \"Request Size/REQ\",\naqu_sz AS \"Queue Size/Q\"\nFROM \"$Table\" WHERE Record = \"$Record\";",
     "rawQueryText": "SELECT dev AS \"Dev\",\ntps AS \"Trans/s\",\ndisk_await AS \"Disk Await\",\npercent_disk_util AS \"Disk Util%\",\nrkB_s AS \"ReadkB/s\",\nwkB_s AS \"WritekB/s\",\ndkB_s AS \"DiskkB/s\",\nareq_sz AS \"Request Size/REQ\",\naqu_sz AS \"Queue Size/Q\"\nFROM \"$Table\" WHERE Record = \"$Record\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Dashboard Style", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Monospaced Fonts On",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 35 },
   "options": {
    "content": "<!-- HTML -->\n<!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css\"> -->\n<style type=\"text/css\">\n  /* CSS */\n  /*\n  @import url(https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css);\n  body { font-family: 'Fira Code', monospace; font-size: 1em; }\n\n  @supports (font-variation-settings: normal) {\n    body { font-family: 'Fira Code VF', monospace; font-size: 1em; }\n  }\n  */\n  body {\n    font-family: Consolas, Monaco, 'Courier New', monospace;\n  }\n</style>\n\nTurn on this to make the dashboard's fonts monospace\n"
   }
  }
 ]
}